spring.application.name=catalogo

spring.application.name=catalogo

server.port=8080

# Conexión a tu base de datos db_urban_clothes
spring.datasource.url=jdbc:postgresql://localhost:5432/db_urban_clothes
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update